### USER:::
###read all users
GET http://localhost:4000/user-api/users


###read a user
GET http://localhost:4000/user-api/user



###create a new user
POST http://localhost:4000/user-api/users
Content-Type: application/json

{
    "username":"pari",
    "password": "pari",
    "email": "pari@gmail.com",
    "age": "19"
}



###update a user
PUT http://localhost:4000/user-api/users/
Content-Type: application/json

{
    "username":"pari",
    "password": "masala coke",
    "email": "pari@gmail.com",
    "age": "18"
}




###delete a user by id
DELETE http://localhost:4000/user-api/users/




### user login/auth
POST http://localhost:4000/user-api/auth
Content-Type: application/json

{
    "email": "pari@gmail.com",
    "password": "pari"
}



### add prod to user cart
PUT  http://localhost:4000/user-api/cart/productId/69b25771dbeb656adf03cbb9

### PRODUCTS::: 

###Create product
POST http://localhost:4000/prod-api/prods
Content-Type: application/json

{
    "productId":102,
    "productName":"shirt",
    "price": 1000,
    "brand": "levi"
}


###read all prods
GET http://localhost:4000/prod-api/prods



###update prod
PUT http://localhost:4000/prod-api/prods
Content-Type: application/json

{
    "productId":101,
    "productName":"shoes",
    "price": "3000 ",
    "brand": "nike",
}



###delete a prod
DELETE http://localhost:4000/prod-api/prods/101
   
