### Create Employee
POST http://localhost:4000/api/emp
Content-Type: application/json

{
  "name": "sam",
  "email": "sam@example.com",
  "mobile": 9876543210,
  "designation": "front dev",
  "companyName": "pintrest"
}

### Get All Employees
GET http://localhost:4000/api/emp

### Update Employee
PUT http://localhost:4000/api/emp/69ca27eb68f1a46f56a0ddb4
Content-Type: application/json

{
  "mobile": 1234567890
}

### Delete Employee
DELETE http://localhost:4000/api